theme = "space-villain"
icons = "awesome"

[[block]]
block = "sound"
name = "bluez_sink.00_1D_DF_B4_C6_78.a2dp_sink"
format = "{volume}%🔈"

[[block]]
block = "sound"
name = "alsa_output.pci-0000_00_1f.3.analog-stereo"
format = "{volume}%🎧"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "disk_space"
path = "/home"
alias = ""
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/"
alias = ""
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_swap = "{SUp}%"
format_mem = "{Mup}%"

[[block]]
block = "memory"
display_type = "swap"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
format = "{barchart} {utilization}%"
interval = 1
# on_click = "htop"

[[block]]
block = "load"
interval = 1
format = "{1m}"


[[block]]
block = "backlight"

[[block]]
block = "networkmanager"



[[block]]
block = "battery"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
