theme = "space-villain"

[icons]
name = "awesome"
[icons.overrides]
music_next=">"
# music_pause="|"
# music_play="~"
# music_prev="<"

[[block]]
block = "music"
buttons = ["prev", "play", "next"]
# player = "spotifyd"
# smart_trim = true
# dynamic_width=true
# on_click = "spd"
on_collapsed_click = "kitty spt"

[[block]]
block = "sound"

[[block]]
block = "bluetooth"
mac = "04:52:C7:C7:DA:C4"
label = " Beats"
# hide_disconnected = true

[[block]]
block = "disk_space"
path = "/home"
alias = ""
info_type = "available"
unit = "Percent"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/"
alias = ""
info_type = "available"
unit = "Percent"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_swap = "{SFpi}%"
format_mem = "{MFpi}%"
clickable = false

[[block]]
block = "memory"
display_type = "swap"
format_mem = "{MFpi}%"
format_swap = "{SFpi}%"
clickable = false

[[block]]
block = "cpu"
format = "{barchart} {utilization}%"
interval = 1
# on_click = "kitty htop"

[[block]]
block = "load"
interval = 1
format = "{1m} {5m}"


[[block]]
block = "backlight"

[[block]]
block = "battery"

[[block]]
block = "networkmanager"
max_ssid_width = 8
# allow_missing = true
# hide_missing = true


[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
