theme = "space-villain"

[icons]
name = "awesome"
# [icons.overrides]
# music_next=">"
# music_pause="|"
# music_play="~"
# music_prev="<"

[[block]]
block = "music"
buttons = ["prev", "play", "next"]
# player = "spotifyd"
smart_trim = true
dynamic_width=true
on_click = "kitty spd"
on_collapsed_click = "kitty spt"

[[block]]
block = "sound"
on_click = "pavucontrol"

[[block]]
block = "bluetooth"
mac = "04:52:C7:C7:DA:C4"
format = "Beats {percentage}"
on_click = "kitty blueman-manager"

[[block]]
block = "bluetooth"
mac = "00:1D:DF:B4:C6:78"
format = "SS"
on_click = "kitty blueman-manager"

[[block]]
block = "disk_space"
path = "/home"
on_click = "kitty dua i /home"
alias = ""
info_type = "available"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/"
on_click = "kitty dua i /"
alias = ""
info_type = "available"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_free_percents:1}"
format_swap = "{swap_free_percents:1}"
on_click = "kitty htop"
clickable = false

[[block]]
block = "memory"
display_type = "swap"
format_mem = "{mem_free_percents:1}"
format_swap = "{swap_free_percents:1}"
clickable = false

[[block]]
block = "cpu"
format = "{barchart} {utilization}%"
interval = 1
on_click = "kitty htop"

[[block]]
block = "load"
interval = 1
format = "{1m} {5m}"
on_click = "kitty htop"


# [[block]]
# block = "backlight"

[[block]]
block = "battery"
allow_missing = true

[[block]]
block = "networkmanager"
on_click = "kitty nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []
ap_format = "{ssid^8}"


[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
on_click = "kitty ikhal"

# [[block]]
# block = "notify"
