	# { on = [ "s" ],         run = "search fd",                                            desc = "Search files by name using fd" },
	# { on = [ "R" ],         run = "search rg",                                            desc = "Search files by content using ripgrep" },
	# { on = [ "<C-s>" ],     run = "search none",                                          desc = "Cancel the ongoing search" },
	# { on = [ "z" ],         run = "jump zoxide",                                          desc = "Jump to a directory using zoxide" },
	# { on = [ "Z" ],         run = "jump fzf",                                             desc = "Jump to a directory, or reveal a file using fzf" },

[[mgr.prepend_keymap]]
on = ["T", "h"]
run = "plugin time-travel --args=prev"
desc = "Go to previous snapshot"

[[mgr.prepend_keymap]]
on = ["T", "l"]
run = "plugin time-travel --args=next"
desc = "Go to next snapshot"

[[mgr.prepend_keymap]]
on = ["T", "e"]
run = "plugin time-travel --args=exit"
desc = "Exit browsing snapshots"

[[mgr.prepend_keymap]]
on   = [ "g", "s" ]
run  = "plugin git-files"
desc = "Show Git file changes"

[[mgr.prepend_keymap]]
on = [ "g", "r" ]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "Go to git root"

[[mgr.prepend_keymap]]
on   = "p"
run  = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"

[[mgr.prepend_keymap]]
on = ["C"]
run = "plugin ouch"
desc = "Compress with ouch"

# version 5.31
# [[mgr.prepend_keymap]]
# on  = "M"
# run = "plugin mount"

# [[mgr.prepend_keymap]]
# on   = "l"
# run  = "plugin smart-enter"
# desc = "Enter the child directory, or open the file"

# [[mgr.prepend_keymap]]
# on   = "f"
# run  = "plugin jump-to-char"
# desc = "Jump to char"

