[mgr]
# layout         = [ 1, 4, 3 ]
# sort_by        = "modified"
# sort_sensitive = true
# sort_reverse   = true
# sort_dir_first = true
# linemode       = "none"
# show_hidden    = true
# show_symlink   = true

[preview]
wrap="yes"
# tab_size        = 2
# max_width       = 600
# max_height      = 900
# cache_dir       = ""
# ueberzug_scale  = 1
# ueberzug_offset = [ 0, 0, 0, 0 ]

[opener]
edit = [
	{ run = '$EDITOR "$@"', block = true,  for = "unix" },
	{ run = 'code "%*"',    orphan = true, for = "windows" },
]
open = [
	{ run = 'xdg-open "$@"',             desc = "Open", for = "linux" },
	{ run = 'open "$@"',                 desc = "Open", for = "macos" },
	{ run = 'start "%1"', orphan = true, desc = "Open", for = "windows" }
]
reveal = [
	{ run = 'open -R "$1"',                       desc = "Reveal", for = "macos" },
	{ run = 'explorer /select,%1', orphan = true, desc = "Reveal", for = "windows" },
	{ run = '''exiftool "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show EXIF", for = "unix" },
]
extract = [
	{ run = 'ouch d "$1"', desc = "Extract here", for = "unix" },
	{ run = 'unar "%1"', desc = "Extract here", for = "windows" },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix", desc = "Play in mpv in background" },
	{ run = 'mpv "%1"', orphan = true, for = "windows", desc = "Play in mpv in background" },
	{ run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info", for = "unix" },
]
play_block = [
	{ run = 'mpv "$@"', block = true, for = "unix", desc = "Play in mpv in foreground" },
	{ run = 'mpv "%1"', block = true, for = "windows", desc = "Play in mpv in foreground" },
	{ run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info", for = "unix" },
]

# [open]
# rules = [
# 	{ name = "*/", use = [ "edit", "open", "reveal" ] },
#
# 	{ mime = "text/*",  use = [ "edit", "reveal" ] },
# 	{ mime = "image/*", use = [ "open", "reveal" ] },
# 	{ mime = "video/*", use = [ "play", "reveal" ] },
# 	{ mime = "audio/*", use = [ "play_block", "play", "reveal" ] },
# 	{ mime = "inode/x-empty", use = [ "edit", "reveal" ] },
#
# 	{ mime = "application/json", use = [ "edit", "reveal" ] },
# 	{ mime = "*/javascript",     use = [ "edit", "reveal" ] },
#
# 	{ mime = "application/zip",             use = [ "extract", "reveal" ] },
# 	{ mime = "application/gzip",            use = [ "extract", "reveal" ] },
# 	{ mime = "application/x-tar",           use = [ "extract", "reveal" ] },
# 	{ mime = "application/x-bzip",          use = [ "extract", "reveal" ] },
# 	{ mime = "application/x-bzip2",         use = [ "extract", "reveal" ] },
# 	{ mime = "application/x-7z-compressed", use = [ "extract", "reveal" ] },
# 	{ mime = "application/x-rar",           use = [ "extract", "reveal" ] },
#
# 	{ mime = "*", use = [ "open", "reveal" ] },
# ]

[plugin]
# ouch plugin
prepend_previewers = [
	{ mime = "application/*zip",            run = "ouch" },
	{ mime = "application/x-bzip2",         run = "ouch" },
	{ mime = "application/x-7z-compressed", run = "ouch" },
	{ mime = "application/x-rar",           run = "ouch" },
	{ mime = "application/vnd.rar",         run = "ouch" },
	{ mime = "application/x-xz",            run = "ouch" },
	{ mime = "application/xz",              run = "ouch" },
	{ mime = "application/x-zstd",          run = "ouch" },
	{ mime = "application/zstd",            run = "ouch" },
	{ mime = "application/java-archive",    run = "ouch" },
	{ mime = "application/x-tar",           run = "ouch" },
]
