# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [
      <nixpkgs/nixos/modules/profiles/qemu-guest.nix>
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/7b9b3756-f25e-4ac9-9390-55b1b84e9dd6";
      fsType = "ext4";
    };

  fileSystems."/data" =
    {
      device = "/dev/disk/by-uuid/8c76029c-5109-4e91-9eb0-1799695715df";
      fsType = "ext4";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/14cfeeb0-c373-4f6e-a0b8-825848d6d4e3"; }];

  nix.settings.max-jobs = lib.mkDefault 2;
}
