use_nerdfont = true
backend = "pulseaudio"
notify = true

[keybindings]
"]" = "seek +5000"
"[" = "seek -5000"
"Ctrl+f" = "move down 10"
"Ctrl+b" = "move up 10"
n = "next"
"Shift+n" = "previous"
q = "queue"
"Shift+q" = "focus queue"
"Shift+l" = "focus library"
"Space" = "playpause"
s = "shuffle"
"+" = "save"
y = "share selected"
"a" = "goto artist"
"Shift+a" = "goto album"
"o" = "open current"
"Shift+J" = "voldown 5"
"Shift+K" = "volup 5"
"Ctrl+q" = "quit"
"Esc" = "back"
